//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWCS.BOMUpload.BLL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BWCS.BOMUpload.BLL.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Create name=&apos;createObject_BillofMaterialComponent&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos;&gt;
        ///       &lt;ApplyTemplate&gt;&lt;![CDATA[(none)]]&gt;&lt;/ApplyTemplate&gt;
        ///       &lt;DomainEntity&gt;
        ///&lt;Key&gt;
        ///&lt;Property path=&apos;site&apos;&gt; 
        ///&lt;Value&gt;&lt;![CDATA[^^site^^]]&gt;&lt;/Value&gt; 
        ///&lt;/Property&gt;
        ///&lt;Property path=&apos;parentItem&apos;&gt;  
        ///&lt;Value&gt;&lt;![CDATA[^^parentItem^^]]&gt;&lt;/Value&gt; 
        ///&lt;/Property&gt;
        ///&lt;Property path=&apos;parentItemRevision&apos;&gt; 
        ///&lt;Value&gt;&lt;![CDATA[^^parentItemRevision^^ ]]&gt;&lt;/Value&gt; 
        ///&lt;/Property&gt;
        ///&lt;Property path=&apos;alternateBomId&apos;&gt; 
        ///&lt;Value&gt;&lt;![C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateBOMComponent {
            get {
                return ResourceManager.GetString("CreateBOMComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Create name=&apos;createObject_BillofMaterial&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterial&apos;&gt;
        ///&lt;ApplyTemplate&gt;&lt;![CDATA[(none)]]&gt;&lt;/ApplyTemplate&gt;
        ///&lt;DomainEntity&gt;
        ///&lt;Key&gt;
        ///         &lt;Property path=&apos;site&apos;&gt; 
        ///         &lt;Value&gt;&lt;![CDATA[^^site^^]]&gt;&lt;/Value&gt; 
        ///         &lt;/Property&gt;
        ///         &lt;Property path=&apos;parentItem&apos;&gt;
        ///         &lt;Value&gt;&lt;![CDATA[^^parentItem^^]]&gt;&lt;/Value&gt;
        ///         &lt;/Property&gt;
        ///         &lt;Property path=&apos;parentItemRevision&apos;&gt;
        ///         &lt;Value&gt;&lt;![CDATA[^^parentItemRevision^^]]&gt;&lt;/Value&gt;
        ///         &lt;/Property&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateBOMHeader {
            get {
                return ResourceManager.GetString("CreateBOMHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Delete name=&apos;deleteObject_BillofMaterialComponent&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos;&gt;
        ///       &lt;DomainEntity&gt;
        ///         &lt;Key&gt;
        ///           &lt;Property path=&apos;site&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^site^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt;
        ///           &lt;Property path=&apos;parentItem&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^parentItem^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt;
        ///           &lt;Property path=&apos;parentItemRevision&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^parentItemRevision^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteBOMComponent {
            get {
                return ResourceManager.GetString("DeleteBOMComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListItemRevision_BOMUPLOADTOOL&apos; domainClass=&apos;com.mapics.epdm.ItemRevision&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1&apos;&gt;
        ///&lt;Pql&gt;&lt;![CDATA[SELECT item,
        ///                  description,
        ///                  drawingNumber,  
        ///                   relatedItemRevisionPurchase.extendedDescription1,
        ///                   relatedItemRevisionPurchase.extendedDescription2,
        ///                   userFieldText40,
        ///                    relatedZ1786B280289768220314AAAAAAAAACZ.oepnix, 
        ///                    revision, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemDetails {
            get {
                return ResourceManager.GetString("GetItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListItemRevision_BOMUPLOADTOOL&apos; domainClass=&apos;com.mapics.epdm.ItemRevision&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1&apos;&gt;
        ///&lt;Pql&gt;&lt;![CDATA[SELECT item,
        ///                  description,
        ///                  drawingNumber,  
        ///                   relatedItemRevisionPurchase.extendedDescription1,
        ///                   relatedItemRevisionPurchase.extendedDescription2,
        ///                   userFieldText40,
        ///                    relatedZ1786B280289768220314AAAAAAAAACZ.oepnix, 
        ///                    revision, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemDetailsByRevision {
            get {
                return ResourceManager.GetString("GetItemDetailsByRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListItemRevision_BOMUPLOADTOOL&apos; domainClass=&apos;com.mapics.epdm.ItemRevision&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1&apos;&gt;
        ///&lt;Pql&gt;&lt;![CDATA[SELECT item,
        ///                  description,
        ///                  drawingNumber,  
        ///                   relatedItemRevisionPurchase.extendedDescription1,
        ///                   relatedItemRevisionPurchase.extendedDescription2,
        ///                   userFieldText40,
        ///                    relatedZ1786B280289768220314AAAAAAAAACZ.oepnix, 
        ///                    relatedCurr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemDetailsCurRevision {
            get {
                return ResourceManager.GetString("GetItemDetailsCurRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListBillofMaterial_General&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterial&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1&apos;&gt;
        ///&lt;Pql&gt;
        ///&lt;![CDATA[SELECT site,relatedItemRevision.itemAccountingClass,
        ///
        ///                          relatedItemRevision.itemType,parentItem,
        ///
        ///                          relatedItemRevision.description,parentItemRevision,
        ///
        ///                          alternateBomId,numberOfComponents,standardBatchQuantity,
        ///
        ///                          relatedItemRevision.currentBasePrice,
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetParentItemRevisionByParentItemSite {
            get {
                return ResourceManager.GetString("GetParentItemRevisionByParentItemSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListBillofMaterialComponent_BOMUPLOAD01&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1000&apos;&gt;
        ///&lt;Pql&gt;
        ///&lt;![CDATA[SELECT 
        ///                      site,
        ///                       parentItem,
        ///                       parentItemRevision,
        ///                       alternateBomId,
        ///                       componentItem,
        ///                       componentItemRevision,
        ///                        token,
        ///                        userSequence1,
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSingleLevelBOM {
            get {
                return ResourceManager.GetString("GetSingleLevelBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListBillofMaterialComponent_BOMUPLOAD01&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1000&apos;&gt;
        ///&lt;Pql&gt;
        ///&lt;![CDATA[SELECT 
        ///                      site,
        ///                       parentItem,
        ///                       parentItemRevision,
        ///                       alternateBomId,
        ///                       componentItem,
        ///                       componentItemRevision,
        ///                        token,
        ///                        userSequence1,
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSingleLevelBOMParentItemRevision {
            get {
                return ResourceManager.GetString("GetSingleLevelBOMParentItemRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Update name=&apos;updateObject_BillofMaterialComponent&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos;&gt;
        ///       &lt;ApplyTemplate&gt;&lt;![CDATA[(none)]]&gt;&lt;/ApplyTemplate&gt;
        ///       &lt;DomainEntity&gt;
        ///         &lt;Key&gt;
        ///           &lt;Property path=&apos;site&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^site^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt;
        ///           &lt;Property path=&apos;parentItem&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^parentItem^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt;
        ///           &lt;Property path=&apos;parentItemRevision&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateBOMComponent {
            get {
                return ResourceManager.GetString("UpdateBOMComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Create name=&apos;createObject_BillofMaterialComponent&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos;&gt;
        ///       &lt;ApplyTemplate&gt;&lt;![CDATA[(none)]]&gt;&lt;/ApplyTemplate&gt;
        ///       &lt;DomainEntity&gt;
        ///&lt;Key&gt;
        ///&lt;Property path=&apos;site&apos;&gt; 
        ///&lt;Value&gt;&lt;![CDATA[^^site^^]]&gt;&lt;/Value&gt; 
        ///&lt;/Property&gt;
        ///&lt;Property path=&apos;parentItem&apos;&gt;  
        ///&lt;Value&gt;&lt;![CDATA[^^parentItem^^]]&gt;&lt;/Value&gt; 
        ///&lt;/Property&gt;
        ///&lt;Property path=&apos;parentItemRevision&apos;&gt; 
        ///&lt;Value&gt;&lt;![CDATA[^^parentItemRevision^^ ]]&gt;&lt;/Value&gt; 
        ///&lt;/Property&gt;
        ///&lt;Property path=&apos;alternateBomId&apos;&gt; 
        ///&lt;Value&gt;&lt;![C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UUCreateBOMComponent {
            get {
                return ResourceManager.GetString("UUCreateBOMComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueryList name=&apos;queryListBillofMaterialComponent_BOMUPLOAD01&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos; includeMetaData=&apos;true&apos; maxReturned=&apos;1000&apos;&gt;
        ///&lt;Pql&gt;
        ///&lt;![CDATA[SELECT 
        ///                      site,
        ///                       parentItem,
        ///                       parentItemRevision,
        ///                       alternateBomId,
        ///                       componentItem,
        ///                       componentItemRevision,
        ///                        token,
        ///                        userSequence2,
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UUGetSingleLevelBOM {
            get {
                return ResourceManager.GetString("UUGetSingleLevelBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Update name=&apos;updateObject_BillofMaterialComponent&apos; domainClass=&apos;com.mapics.epdm.BillOfMaterialComponent&apos;&gt;
        ///       &lt;ApplyTemplate&gt;&lt;![CDATA[(none)]]&gt;&lt;/ApplyTemplate&gt;
        ///       &lt;DomainEntity&gt;
        ///         &lt;Key&gt;
        ///           &lt;Property path=&apos;site&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^site^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt;
        ///           &lt;Property path=&apos;parentItem&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA[^^parentItem^^]]&gt;&lt;/Value&gt;
        ///           &lt;/Property&gt;
        ///           &lt;Property path=&apos;parentItemRevision&apos;&gt;
        ///             &lt;Value&gt;&lt;![CDATA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UUUpdateBOMComponent {
            get {
                return ResourceManager.GetString("UUUpdateBOMComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Login userId=&apos;{0}&apos; password=&apos;{1}&apos; maxIdle=&apos;{2}&apos; properties=&apos;com.pjx.cas.domain.EnvironmentId={3},com.pjx.cas.domain.SystemName={4},com.pjx.cas.user.LanguageId=en&apos;/&gt;.
        /// </summary>
        internal static string XALogin {
            get {
                return ResourceManager.GetString("XALogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Login userId=&apos;{0}&apos; password=&apos;{1}&apos; maxIdle=&apos;0&apos; properties=&apos;com.pjx.cas.domain.EnvironmentId={3},com.pjx.cas.domain.SystemName={4},com.pjx.cas.user.LanguageId=en&apos;/&gt;.
        /// </summary>
        internal static string XALoginTEST {
            get {
                return ResourceManager.GetString("XALoginTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Logout sessionHandle=&apos;{0}&apos;/&gt;.
        /// </summary>
        internal static string XALogOut {
            get {
                return ResourceManager.GetString("XALogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Request sessionHandle=&apos;{0}&apos; workHandle=&apos;*new&apos;
        ///          broker=&apos;EJB&apos; maxIdle=&apos;10000&apos;&gt;{1}&lt;/Request&gt;.
        /// </summary>
        internal static string XARequest {
            get {
                return ResourceManager.GetString("XARequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Request sessionHandle=&apos;{0}&apos; workHandle=&apos;*new&apos;
        ///          broker=&apos;EJB&apos; maxIdle=&apos;0&apos;&gt;{1} &lt;Logout sessionHandle=&apos;{0}&apos;/&gt; &lt;/Request&gt;.
        /// </summary>
        internal static string XARequestTEST {
            get {
                return ResourceManager.GetString("XARequestTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;ISO-8859-1&apos;?&gt;&lt;!DOCTYPE System-Link SYSTEM &quot;SystemLinkRequest.dtd&quot;&gt;&lt;System-Link&gt;{0}&lt;/System-Link&gt;.
        /// </summary>
        internal static string XASystemLinkRequest {
            get {
                return ResourceManager.GetString("XASystemLinkRequest", resourceCulture);
            }
        }
    }
}
